[font]
size = 11

[font.bold]
family = "0xProto Nerd Font Mono"

[font.bold_italic]
family = "0xProto Nerd Font Mono"

[font.italic]
family = "0xProto Nerd Font Mono"

[font.normal]
family = "0xProto Nerd Font Mono"
